project_id = "fjrxqeyexlusjwzzecal"

[functions.generate-learning-visual]
verify_jwt = true

[functions.process-receipt]
verify_jwt = true

[functions.send-receipt-report]
verify_jwt = false

[functions.paypal-create-order]
verify_jwt = true

[functions.paypal-capture-order]
verify_jwt = true

[functions.create-download-purchase-paypal]
verify_jwt = false

[functions.capture-download-purchase-paypal]
verify_jwt = false

[functions.smart-categorize]
verify_jwt = true
